workflows:
  breeze-stories-api:
    name: Deploy API
    environment:
      groups:
        - cloudinary
        - token
        - mongo-db
        - urls
    scripts:
        - npm i
        - npm run build
        - npm run start
